### ISSUE TITLE
update to numpy 1.24

### ISSUE THREAD

**Issue by WreckItTim** [faridyagubbayli/binvox#3]
great lib, can you please update to numpy 1.24. Thank you!

**Comment by faridyagubbayli** [comment]
Hey Tim! Thanks for letting me know about this issue.

I just fixed the installation process and made a new release ([1.6.0](https://github.com/faridyagubbayli/binvox/releases/tag/release-0.1.6)). It is live on [pypi](https://pypi.org/project/binvox/) and you can install it using `pip install binvox`. Please feel free to re-open the issue if the fix doesn't work for you.

**Comment by egidioln** [comment]
Hello @faridyagubbayli,

Thanks for this support. I'm still facing some incompatibility with numpy 1.24. For example, the following code crashes:
```python
import numpy as np
from binvox import Binvox
bv = Binvox(axis_order="xyz", data=np.ones((3,3,3)))
bv.to_sparse()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\binvox\binvox.py", line 195, in to_sparse
    self.data = np.asarray(np.nonzero(self.data), np.int)
  File "...\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```



The `np.int` alias for `int` was [deprecated](https://github.com/numpy/numpy/pull/22607). Could we maybe change these four lines (`np.int` -> `int` or `np.int32`)?

https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/binvox/binvox.py#L195
https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/binvox/binvox.py#L210

https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/tests/binvox_rw_original.py#L203
https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/tests/binvox_rw_original.py#L218


Cheers

**Comment by egidioln** [comment]
Oups, and also these four (`np.bool` -> `bool`)

https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/binvox/binvox.py#L86
https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/binvox/binvox.py#L119

https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/tests/binvox_rw_original.py#L143
https://github.com/faridyagubbayli/binvox/blob/600ae6c724c117a59d90b4868e460ca885f7e93d/tests/binvox_rw_original.py#L177

**Comment by WreckItTim** [comment]
Hello, yes the problem still persists. Just need to switch all of the "np.bool" with "bool" and it will run fine on new numpy. Can you please update the repo so that pip install reflects this - currently it does not.
